### PR TITLE
feat: add REPL support

### PR DESCRIPTION
**Pull request by sloboegen**
I got some free time and wanted to do something useful for this project:) I haven’t written in OCaml for a long time, so the code can be ugly in places...

This PR contains a REPL (#18) implementation based on [lambda-term](https://github.com/ocaml-community/lambda-term) library. More information about REPL features can be found in [this README](https://github.com/mtt-lang/mtt-lang/blob/repl/repl/README.md).

### **Small demo:**
mttrepl

### **Some remarks:**

1. Same code duplication problem as `mttweb.ml` (function `eval_repl`, `infer_repl` and `parse_repl`). Maybe I'll try to fix it!
2. Probably, it makes sense adding support for global variable names, so as not to write one big term. With this feature, using REPL will be more convenient!

### CODE REVIEW

**Comment by anton-trunov** [comment]
Wow! This is impressive!

**Comment by anton-trunov** [comment]
Just one small request: can we make `repl` a subcommand of `mtt`? So that one could run it as `mtt repl`

**Comment by sloboegen** [comment]
> Just one small request: can we make `repl` a subcommand of `mtt`? So that one could run it as `mtt repl`

Done!

**Review by anton-trunov — APPROVED** [review]

**Comment by anton-trunov** [comment]
Great feature! Thanks a bunch!

**Pull request merged**
